name: FrontBot

on:
  workflow_call:
    inputs:
      assignees:
        type: string

      committer:
        required: true
        type: string

      workingDirectory:
        type: string
        default: '.'

      updateRequiredPhp:
        type: boolean
        default: false

      minimalRequiredPhp:
        type: string
        default: '7.4'

      maximalRequiredPhp:
        type: string
        default: '8.3'

    secrets:
      FRONTBOT_TOKEN:
        required: true

      COMPOSER_AUTH_CONFIG:
        required: false

jobs:
    frontbot:
        name: FrontBot
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.workingDirectory }}
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  coverage: none

            - name: 'Configure Composer Auth'
              env:
                COMPOSER_AUTH_CONFIG: ${{ secrets.COMPOSER_AUTH_CONFIG }}
              if: ${{ env.COMPOSER_AUTH_CONFIG != '' }}
              run: printenv COMPOSER_AUTH_CONFIG > ./auth.json

            - name: 'Configure Git User'
              run: |
                git config user.name "$(echo "${{ inputs.committer }}" | sed "s/[<>]/\n/g" | sed 1q)"
                git config user.email "$(echo "${{ inputs.committer }}" | sed "s/[<>]/\n/g" | sed -e 1d -e 2q)"

            - name: 'Composer Installation of Dependencies'
              run: composer install --no-interaction --prefer-dist

            - name: Code Checker Installation
              run: composer create-project janpecha/code-checker ${{ runner.temp }}/code-checker --no-progress

            - name: Code Checker Fixes
              run: ${{ runner.temp }}/code-checker/code-checker --fix --git --no-progress

            - name: Update of required PHP versions
              if: ${{ inputs.updateRequiredPhp }}
              run: |
                composer require php "${{ inputs.minimalRequiredPhp }} - ${{ inputs.maximalRequiredPhp }}"
                ${{ runner.temp }}/code-checker/code-checker --fix --no-progress
                git commit -m "Updated required PHP ${{ inputs.minimalRequiredPhp }} - ${{ inputs.maximalRequiredPhp }}"

            - name: Composer Updater Installation
              run: composer create-project janpecha/composer-updater ${{ runner.temp }}/composer-updater --no-progress

            - name: Composer Updater Execution
              run: ${{ runner.temp }}/composer-updater/composer-updater update

            - name: Code Checker Upgrade Fixes
              run: ${{ runner.temp }}/code-checker/code-checker --fix --no-progress

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.FRONTBOT_TOKEN }}
                  commit-message: "Composer: updated dependencies"
                  branch: frontbot/updates
                  delete-branch: true
                  title: 'FrontBot: project upgrade'
                  body: "Project auto-upgraded by FrontBot"
                  assignees: ${{ inputs.assignees }}
                  author: ${{ inputs.committer }}
                  committer: ${{ inputs.committer }}
