name: FrontBot

on:
  workflow_call:
    inputs:
      assignees:
        type: string

      committer:
        required: true
        type: string

      workingDirectory:
        type: string
        default: '.'

    secrets:
      FRONTBOT_TOKEN:
        required: true

      COMPOSER_AUTH_CONFIG:
        required: false

jobs:
    frontbot:
        name: FrontBot
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.workingDirectory }}
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  coverage: none

            -
              env:
                COMPOSER_AUTH_CONFIG: ${{ secrets.COMPOSER_AUTH_CONFIG }}
              if: ${{ env.COMPOSER_AUTH_CONFIG != '' }}
              run: printenv COMPOSER_AUTH_CONFIG > ./auth.json

            - run: composer create-project janpecha/composer-updater ${{ runner.temp }}/composer-updater --no-progress
            - run: ${{ runner.temp }}/composer-updater/composer-updater update

            - run: composer create-project janpecha/code-checker ${{ runner.temp }}/code-checker --no-progress
            - name: Code Checker Fixes
              run: ${{ runner.temp }}/code-checker/code-checker --fix --no-progress

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.FRONTBOT_TOKEN }}
                  commit-message: "Composer: updated dependencies"
                  branch: frontbot/updates
                  delete-branch: true
                  title: 'FrontBot: updated dependencies'
                  body: "Auto-updated dependencies"
                  assignees: ${{ inputs.assignees }}
                  author: ${{ inputs.committer }}
                  committer: ${{ inputs.committer }}
