name: Nette Tester

on:
  workflow_call:
    inputs:
      phpVersions:
        required: true
        type: string

      testsDirectory:
        type: string
        default: 'tests'

      lowestDependencies:
        type: boolean
        default: true

      workingDirectory:
        type: string
        default: '.'

    secrets:
      COMPOSER_AUTH_CONFIG:
        required: false

jobs:
    tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.workingDirectory }}
        strategy:
            matrix:
                php: ${{ fromJson(inputs.phpVersions) }}

            fail-fast: false

        name: PHP ${{ matrix.php }} tests
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            -
              env:
                COMPOSER_AUTH_CONFIG: ${{ secrets.COMPOSER_AUTH_CONFIG }}
              if: ${{ env.COMPOSER_AUTH_CONFIG != '' }}
              run: printenv COMPOSER_AUTH_CONFIG > ./auth.json

            - run: composer install --no-interaction --prefer-dist
            - run: vendor/bin/tester ${{ inputs.testsDirectory }} -s -C
            - if: failure()
              uses: actions/upload-artifact@v2
              with:
                  name: output
                  path: tests/**/output


    lowest_dependencies:
        if: ${{ inputs.lowestDependencies }}
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.workingDirectory }}
        strategy:
            matrix:
                php: ${{ fromJson(inputs.phpVersions) }}

            fail-fast: false

        name: PHP ${{ matrix.php }} tests - lowest dependencies
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            -
              env:
                COMPOSER_AUTH_CONFIG: ${{ secrets.COMPOSER_AUTH_CONFIG }}
              if: ${{ env.COMPOSER_AUTH_CONFIG != '' }}
              run: printenv COMPOSER_AUTH_CONFIG > ./auth.json

            - run: composer update --no-interaction --prefer-dist --prefer-lowest --prefer-stable
            - run: vendor/bin/tester ${{ inputs.testsDirectory }} -s -C
            - if: failure()
              uses: actions/upload-artifact@v2
              with:
                  name: output
                  path: tests/**/output
